-- ================================================================
-- Real-Time Network Intrusion Detection System
-- Database Schema
-- ================================================================

-- Drop database if exists (BE CAREFUL IN PRODUCTION!)
DROP DATABASE IF EXISTS ids_database;

-- Create database
CREATE DATABASE ids_database 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

USE ids_database;

-- ================================================================
-- Table 1: ALERTS
-- Stores all security alerts generated by the detection engine
-- ================================================================
CREATE TABLE alerts (
    alert_id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_ip VARCHAR(45) NOT NULL COMMENT 'Source IP address (IPv4 or IPv6)',
    dest_ip VARCHAR(45) NOT NULL COMMENT 'Destination IP address',
    source_port INT COMMENT 'Source port number',
    dest_port INT COMMENT 'Destination port number',
    protocol VARCHAR(10) NOT NULL COMMENT 'Protocol: TCP, UDP, ICMP, etc.',
    attack_type VARCHAR(50) NOT NULL COMMENT 'Type of attack detected',
    severity ENUM('Low', 'Medium', 'High', 'Critical') NOT NULL,
    risk_score INT NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    confidence_score DECIMAL(5,2) COMMENT 'Detection confidence percentage',
    detection_method VARCHAR(20) NOT NULL COMMENT 'Rule-based, ML-based, or Hybrid',
    packet_count INT DEFAULT 1 COMMENT 'Number of packets in this alert',
    additional_context TEXT COMMENT 'Human-readable description',
    
    -- Indexes for performance
    INDEX idx_timestamp (timestamp),
    INDEX idx_source_ip (source_ip),
    INDEX idx_severity (severity),
    INDEX idx_attack_type (attack_type),
    INDEX idx_risk_score (risk_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Security alerts from IDS';

-- ================================================================
-- Table 2: IP_REPUTATION
-- Tracks IP address behavior over time
-- ================================================================
CREATE TABLE ip_reputation (
    ip_address VARCHAR(45) PRIMARY KEY COMMENT 'IP address (unique)',
    alert_count INT DEFAULT 0 COMMENT 'Total alerts from this IP',
    first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    total_risk_score INT DEFAULT 0 COMMENT 'Sum of all risk scores',
    avg_risk_score DECIMAL(5,2) COMMENT 'Average risk score',
    is_whitelisted BOOLEAN DEFAULT FALSE COMMENT 'Is IP whitelisted?',
    
    INDEX idx_alert_count (alert_count),
    INDEX idx_last_seen (last_seen),
    INDEX idx_is_whitelisted (is_whitelisted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IP address reputation tracking';

-- ================================================================
-- Table 3: TRAFFIC_STATS
-- Stores aggregated traffic statistics
-- ================================================================
CREATE TABLE traffic_stats (
    stat_id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_packets INT DEFAULT 0,
    total_bytes BIGINT DEFAULT 0,
    avg_packet_rate FLOAT COMMENT 'Packets per second',
    protocol_distribution JSON COMMENT 'JSON object with protocol counts',
    alerts_generated INT DEFAULT 0 COMMENT 'Alerts in this time period',
    
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Aggregated traffic statistics';

-- ================================================================
-- Table 4: CONFIGURATION
-- System configuration parameters
-- ================================================================
CREATE TABLE configuration (
    config_key VARCHAR(50) PRIMARY KEY,
    config_value TEXT NOT NULL,
    data_type VARCHAR(20) NOT NULL COMMENT 'integer, float, string, boolean',
    category VARCHAR(50) COMMENT 'detection, risk_scoring, system',
    description VARCHAR(200),
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System configuration';

-- ================================================================
-- Table 5: SERVICE_MAPPING
-- Maps ports to services and criticality scores
-- ================================================================
CREATE TABLE service_mapping (
    port_number INT PRIMARY KEY,
    service_name VARCHAR(50) NOT NULL,
    protocol VARCHAR(10) NOT NULL COMMENT 'TCP or UDP',
    criticality_score INT NOT NULL CHECK (criticality_score BETWEEN 15 AND 25),
    description VARCHAR(200),
    is_well_known BOOLEAN DEFAULT TRUE COMMENT 'Is this a well-known port?',
    
    INDEX idx_service_name (service_name),
    INDEX idx_criticality (criticality_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Service-to-port mapping with criticality';

-- ================================================================
-- Table 6: WHITELIST
-- Trusted IP addresses that should not trigger alerts
-- ================================================================
CREATE TABLE whitelist (
    entry_id INT AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL UNIQUE,
    description VARCHAR(200),
    added_by VARCHAR(50) COMMENT 'Username or system',
    added_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    
    INDEX idx_ip_address (ip_address),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Whitelisted IP addresses';

-- ================================================================
-- Verify tables created
-- ================================================================
SHOW TABLES;
